eureka:
  client:
    service-url:
      defaultZone: http://eureka-server.default.svc.cluster.local:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true  

spring:
  application:
    name: api-gateway  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors: 
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true  
            exposedHeaders: "Authorization"  
      routes:
        
        - id: authentification-service
          uri: lb://authentification-service.default.svc.cluster.local:8888
          predicates:
            - Path=/api/auth/**,/authentification/**  
          filters:
            - StripPrefix=1 
            - RewritePath=/authentification/(?<path>.*), /$\{path}

       
        - id: ter-logement-service
          uri: lb://ter-logement-service.default.svc.cluster.local:8888
          predicates:
            - Path=/api/logement/**,/logement/** 
          filters:
            - StripPrefix=1
            - RewritePath=/logement/(?<path>.*), /$\{path}

       
        - id: payment-microservice
          uri: lb://payment-microservice
          predicates:
            - Path=/payment/**
          filters:
            - RewritePath=/payment/(?<path>.*), /$\{path}

       
        - id: openapi
          uri: http://api-gateway:${server.port} 
          predicates:
            - Path=/v3/api-docs/**,/swagger-ui/**,/swagger-ui.html  

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:  # From new config
        allowed-origins: "*"
        allowed-methods: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
