eureka:
  client:
    service-url:
      defaultZone: http://eureka-server.default.svc.cluster.local:8761/eureka/ 
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true  

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: microservice-authentification
          uri: lb://microservice-authentification  
          predicates:
            - Path=/api/auth/**  
          filters:
            - StripPrefix=1  
            
        - id: microservice-logement
          uri: lb://microservice-logement
          predicates:
            - Path=/api/logement/**  
          filters:
            - StripPrefix=1
            
        # OpenAPI/Swagger config (updated for Kubernetes)
        - id: openapi
          uri: http://api-gateway:${server.port} 
          predicates:
            - Path=/v3/api-docs/**,/swagger-ui/**

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"  
        allowed-methods: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true